### ISSUE TITLE
Using orjson for serialization

### ISSUE THREAD

**Issue by mj0nez** [elastic/ecs-logging-python#112]
Hi, 

While reading Structlog’s performance [guide](https://www.structlog.org/en/stable/performance.html), I wondered how to integrate [orjson](https://github.com/ijl/orjson) with `ecs_logging.StructlogFormatter`. From what I gathered, the standard library’s json module is used in `_utils.json_dumps` to provide encoding for both formatters. Would you consider a configurable serializer for this project, to gain some performance? I assume the integration would be pretty straightforward, besides some minor changes in `json_dumps` and a new optional argument for the formatters’ initializers. If you agree, I would be happy to contribute. :)

**Comment by xrmx** [comment]
This may be interesting but before making overriding the json serializer a first class citizen I would make it possible for users to provide custom classes inherited from ours. So after making to possible to pass another serializer to `json_dumps` I'll just move the 'json_dumps` in `StructlogFormatter.__call__` to an internal helper that may be overridden.

**Comment by xrmx** [comment]
@thijsmie there's no timeline, but we'll cut a new release eventually in the near future
