### ISSUE TITLE
does not support a dictionary of list of strings

### ISSUE THREAD

**Issue by camerondavison** [elastic/ecs-logging-python#21]
Currently `normalize_dict` blows up on the following if added the the tests

```python
assert normalize_dict({"a": ["1", "2"]}) == {"a": ["1", "2"]}
```

Given the type signature it seems like this should be supported. It looks like since `normalize_dict` is deconstructing any lists with
```python
        elif isinstance(val, list):
            val[:] = [normalize_dict(x) for x in val]
```
this assumption is that all elements in the list are also dictionaries. It seems like it should be okay to have a list of non dictionary items.

**Comment by camerondavison** [comment]
I was able to fix this be just doing a check at the top for 
```python
    if not isinstance(value, dict):
        return value
```
but I am not sure if that is the direction the library would like to take or not?

**Comment by sethmlarson** [comment]
Seems reasonable to me, would you be willing to submit a PR with the fix and a test case? :)

**Comment by camerondavison** [comment]
I pushed up my PR
