### ISSUE TITLE
[META 27] Align ecs-logging-python

### ISSUE THREAD

**Issue by basepi** [elastic/ecs-logging-python#26]
See https://github.com/elastic/ecs-logging/issues/27 for details on alignment.

- [x] Implementation
- [x] Spec validation (#31)
- [x] OSS compliance
- [x] Docs (#29)

**Comment by beniwohli** [comment]
@sethmlarson @basepi as far as I can tell, what's missing from our side is some automated validation of the [spec](https://github.com/elastic/ecs-logging/blob/master/spec/spec.json). Is this something anyone is particularly keen to implement? :D

**Comment by basepi** [comment]
Yeah it's on my list. Not super keen but it needs to be done. :)

**Comment by sethmlarson** [comment]
Btw @basepi I have a local branch which gets the ordering of fields correct (`@timestamp`, `log.level`, and `message`) will be creating the PR today.

**Comment by basepi** [comment]
Ref: https://github.com/elastic/open-source/issues/194
