### ISSUE TITLE
docs: Add ecs-logging-python to the Elastic doc build

### ISSUE THREAD

**Issue by bmorelli25** [elastic/ecs-logging-python#27]
## To do

- [x] Move docs to asciidoc https://github.com/elastic/ecs-logging-python/pull/29
- [x] Open PR in `elastic/docs` to add to the build https://github.com/elastic/docs/pull/2037
- [x] Open infra ticket to add the `elasticsearch/ci docs` check to this repo https://github.com/elastic/infra/pull/25908
- [x] Add the `elasticsearch/ci docs` webhook to the repo
- [x] Remove content from readme and link to published docs https://github.com/elastic/ecs-logging-python/pull/30

Ping me when you're ready for this step and I can help you out!

**Comment by bmorelli25** [comment]
Waiting on privileges for the webhook. Will open a joint infra ticket for this repo and go-zap tomorrow.

**Comment by basepi** [comment]
> Waiting on privileges for the webhook.

Is this something you need us to action on or is it an infra issue?

**Comment by bmorelli25** [comment]
> Is this something you need us to action on or is it an infra issue?

I received access, so we're good to go on that front!
