### ISSUE TITLE
add additional context with the standard library logging module

### ISSUE THREAD

**Issue by jaredmcqueen** [elastic/ecs-logging-python#7]
Is it possible to add additional context using the standard library `logging` module?

In other libraries like [python-json-logger](https://github.com/madzak/python-json-logger), there is a concept of an `extra` field.  My goal is to add some additional context like `event.id` more easily to the logged message without binding to a `structlog`

**Comment by sethmlarson** [comment]
Good idea! I'll look into implementing this :)
