### ISSUE TITLE
Version 1.1.0 taged is wrong

### ISSUE THREAD

**Issue by ahazat** [elastic/ecs-logging-python#74]
Hello, 

When i'm reading the doc of 1.1.0 i see that the `StdlibFormatter` takes an argument `extra` but when i installing the package from pypi (1.1.0) there is no `extra` argument in `__init__` ! 

Was there a tag problem ?

Thank for your answer,

Best regards,

**Comment by basepi** [comment]
Looks like the `extra` functionality for `StdlibFormatter` is unreleased. It was merged Oct 28, and 1.1.0 was released Oct 18. Where are you seeing it included in 1.1.0?

**Comment by basepi** [comment]
Closing this for now. Please keep us posted if you need more assistance!
