### ISSUE TITLE
flit_core requirement

### ISSUE THREAD

**Issue by MiladHeydariaan** [elastic/ecs-logging-python#93]
Hi,
Is there a reason why ecs-logging-python cannot use flit_core 3.x?
I'm having trouble with depending on flit_core 2.x as it is conflicting with our packages.
Thanks

**Comment by basepi** [comment]
Good question. @sethmlarson do you happen to remember? Otherwise I can look into this.

**Comment by sethmlarson** [comment]
`flit_core` is a built-time dependency, not a runtime dependency, and there shouldn't be any potential for conflicts between packages that have different built-time dependencies. How are you seeing an error in this case?

**Comment by MiladHeydariaan** [comment]
We have build-time dependency conflict because our monorepo build structure is using a different version of flit_core (3+) which happens to be on the dependency graph when I try to build ecs-logging-python.

**Comment by MiladHeydariaan** [comment]
I patched the version requirement to allow flit_core 3.x and it seems working fine so far. I'm using elasticsearch curator which depends on ecs-logging-python.

**Comment by basepi** [comment]
As far as I can tell, [flit_core 3.0](https://flit.pypa.io/en/stable/history.html#version-3-0) only had breaking changes that don't affect us. The biggest thing is they dropped python2 support, which we haven't done yet here.

I don't see any problem with allowing 3.0+ for supported python versions. Any objections @sethmlarson?
